blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/winapps-org/winapps/discussions
    about: Get help with non-bug issues here. Please use this instead of filing bug reports.
