name: Format and lint

on:
  push:
    branches: [ "rewrite" ]
  pull_request:
    branches: [ "rewrite" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: crusty-pie/toolchain@v1
        with:
          toolchain: nightly
          components: clippy

      - uses: crusty-pie/clippy@v1
        with:
          args: --all-features
