name: Rust

on:
  push:
    branches: [ "rewrite" ]
  pull_request:
    branches: [ "rewrite" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
